# Generated by Django 4.2.1 on 2023-08-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplierId',
            new_name='supplier',
        ),
    ]
